services:
  database:
    env_file:
      - .env
    image: postgres:16-alpine
    healthcheck:
      interval: 1s
      test: 'pg_isready --username=postgres'
    ports:
      - '5450:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: backend
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - '3000:3000'

  frontend:
    build: frontend
    ports:
      - '80:80'
    restart: always
    depends_on:
      - backend
